

spring:

  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  
  devtools.livereload.enabled: true

  data.rest.base-path: /api

  codec.max-in-memory-size: 10MB